language: python
python:
- '3.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

install:
- pip install python-coveralls
- pip install pytest-cov pytest-pep8
- pip install -e .

script:
- pytest
